### ISSUE TITLE
Embiggening the osm data bbox in buildOsm.ts?

### ISSUE THREAD

**Issue by dvorakroth** [danfishgold/bike-map#1]
Hi!

I was wondering if you'd be open to embiggening the bounding box in the buildOsm script? I like to use this map with the OSM data layer, and currently it doesn't even extend south past Holon, which is a problem for me as I sometimes bike to Rishon. :)

I tried running the script with the bounding box 31.754221599391386,34.57095877961163, 32.427726648606026,35.10895164708501 which I drew manually to enclose the entire Central District

<img width="500" alt="A map of central Israel with both the previous bounding box, and the much, much bigger bounding box I used" src="https://user-images.githubusercontent.com/4295016/198252687-b19b7031-cd74-4d88-88bb-912d059bc448.png">

But then predictably, the resulting data file grew from 2 MB to 5.4 MB, and now it also includes a whole bunch of paths around Modi'in that I'm not entirely sure are actual bike paths in the urban sense

<img width="350" alt="Modi'in surrounded by squiggly bike paths in the forest" src="https://user-images.githubusercontent.com/4295016/198253711-08f848ab-9422-4d9d-8d2d-b47a73f3a9da.png">

So there's definitely a trade off to be had here; and I don't know what the considerations for choosing the original bounding box actually were, so maybe the one I used looks outlandish and unrealistic :) But I'd still love it if it could be embiggened enough to include Rishon, and some of the other not-so-distant parts of Gush Dan.

Thanks for the map!

**Comment by danfishgold** [comment]
OOPS I should check my GH notifications more often ☹️

Thanks for looking into this! When I wrote the script I didn't know much about Overpass but now I know that I can use OSM areas/relations instead of a bounding box! (Plus I didn't know how to remove extra data I wasn't using)

When I query inside the Tel Aviv District (rel 1400916) and the Central District (rel 1400928) I get a 3.6MB file, and Ben Shemen forest (rel 1638371) accounts for abut 0.5MB of that, so all in all I think 3.1MB is manageable 😄

**Comment by danfishgold** [comment]
Done!
Thanks @dvorakroth 😄
I removed a bunch of forests and got it to 2.6MB. There are still a bunch of weird tiny paths, but at least it won't substantially impact loading time
